//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.05 at 04:42:20 PM GMT+04:00 
//


package com.sm.bpelmodeller.config.xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sm.bpelmodeller.config.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BpelStoModelConfiguration_QNAME = new QName("http://sm.com/bpel/stomodel-config", "BpelStoModelConfiguration");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sm.bpelmodeller.config.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TTimeDistribution }
     * 
     */
    public TTimeDistribution createTTimeDistribution() {
        return new TTimeDistribution();
    }

    /**
     * Create an instance of {@link TIfBranchConfig }
     * 
     */
    public TIfBranchConfig createTIfBranchConfig() {
        return new TIfBranchConfig();
    }

    /**
     * Create an instance of {@link TActivityConfig }
     * 
     */
    public TActivityConfig createTActivityConfig() {
        return new TActivityConfig();
    }

    /**
     * Create an instance of {@link TAtomicActivityConfig }
     * 
     */
    public TAtomicActivityConfig createTAtomicActivityConfig() {
        return new TAtomicActivityConfig();
    }

    /**
     * Create an instance of {@link TFlowActivityConfig }
     * 
     */
    public TFlowActivityConfig createTFlowActivityConfig() {
        return new TFlowActivityConfig();
    }

    /**
     * Create an instance of {@link StoModelConfig }
     * 
     */
    public StoModelConfig createStoModelConfig() {
        return new StoModelConfig();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StoModelConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sm.com/bpel/stomodel-config", name = "BpelStoModelConfiguration")
    public JAXBElement<StoModelConfig> createBpelStoModelConfiguration(StoModelConfig value) {
        return new JAXBElement<StoModelConfig>(_BpelStoModelConfiguration_QNAME, StoModelConfig.class, null, value);
    }

}
