//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.05 at 04:42:20 PM GMT+04:00 
//


package com.sm.bpelmodeller.config.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TAtomicActivityConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TAtomicActivityConfig">
 *   &lt;complexContent>
 *     &lt;extension base="{http://sm.com/bpel/stomodel-config}TActivityConfig">
 *       &lt;sequence>
 *         &lt;element name="TimeDistribution" type="{http://sm.com/bpel/stomodel-config}TTimeDistribution" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TAtomicActivityConfig", propOrder = {
    "timeDistribution"
})
public class TAtomicActivityConfig
    extends TActivityConfig
{

    @XmlElement(name = "TimeDistribution", required = true)
    protected List<TTimeDistribution> timeDistribution;

    /**
     * Gets the value of the timeDistribution property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timeDistribution property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTimeDistribution().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TTimeDistribution }
     * 
     * 
     */
    public List<TTimeDistribution> getTimeDistribution() {
        if (timeDistribution == null) {
            timeDistribution = new ArrayList<TTimeDistribution>();
        }
        return this.timeDistribution;
    }

}
